version: '3.8'

services:
  servicea:
    build:
      context: ./serviceA
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - meuservico-network

  serviceb:
    build:
      context: ./serviceB
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    networks:
      - meuservico-network

  otel-collector:
    image: otel/opentelemetry-collector:latest
    command: ["--config=/etc/otel-collector-config.yaml"]
    volumes:
      - ./otel-collector-config.yaml:/etc/otel-collector-config.yaml
    ports:
      - "4317:4317"
      - "55681:55681"
    networks:
      - meuservico-network

  prometheus:
    image: prom/prometheus:latest
    volumes:
      - ./prometheus.yaml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"
    networks:
      - meuservico-network

  jaeger:
    image: jaegertracing/all-in-one:latest
    ports:
      - "5775:5775/udp"
      - "6831:6831/udp"
      - "6832:6832/udp"
      - "5778:5778"
      - "16686:16686"
      - "14268:14268"
      - "14250:14250"
      - "9411:9411"
    networks:
      - meuservico-network

networks:
  meuservico-network:
    driver: bridge
