version: '3.8'

services:
  jaeger-all-in-one:
    image: jaegertracing/all-in-one:latest
    ports:
      - "16686:16686"
      - "14268"
      - "14250"
    networks:
      - servicos-network

  prometheus:
    container_name: prometheus
    image: prom/prometheus:latest
    restart: always
    volumes:
      - ./.docker/prometheus.yaml:/etc/prometheus/prometheus.yml
    ports:
      - "9090:9090"

  otel-collector:
    image: otel/opentelemetry-collector:latest
    restart: always
    command: ["--config=/etc/otel-collector-config.yaml"]
    volumes:
      - ./.docker/otel-collector-config.yaml:/etc/otel-collector-config.yaml
    ports:
      - "8888:8888"
      - "8889:8889"
      - "4317:4317"
    networks:
      - servicos-network

  servicea:
    build:
      context: ./serviceA
      dockerfile: Dockerfile
    environment:
      - REQUEST_NAME_OTEL=service-a
      - OTEL_SERVICE_NAME=service-a
      - OTEL_EXPORTER_OTLP_ENDPOINT=otel-collector:4317
      - HTTP_PORT=8080
    ports:
      - "8080:8080"
    depends_on:
      - jaeger-all-in-one
      - prometheus
      - otel-collector
    networks:
      - servicos-network

  serviceb:
    build:
      context: ./serviceB
      dockerfile: Dockerfile
    environment:
      - REQUEST_NAME_OTEL=service-b
      - OTEL_SERVICE_NAME=service-b
      - OTEL_EXPORTER_OTLP_ENDPOINT=otel-collector:4317
      - HTTP_PORT=8081
    ports:
      - "8081:8081"
    depends_on:
      - jaeger-all-in-one
      - prometheus
      - otel-collector
    networks:
      - servicos-network

networks:
  servicos-network:
    driver: bridge
