version: '3.8'

services:
  servicea:
    build:
      context: ./serviceA
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    networks:
      - servicos-network

  serviceb:
    build:
      context: ./serviceB
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    networks:
      - servicos-network

networks:
  servicos-network:
    driver: bridge
