receivers:
  otlp:
    protocols:
      grpc:
      http:

exporters:
  zipkin:
    endpoint: "http://zipkin:9411/api/v2/spans"  # Note que a porta correta é 9411

service:
  pipelines:
    traces:
      receivers: [otlp]
      exporters: [zipkin]
